version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - sudo apt install ttf-mscorefonts-installer
      - sudo fc-cache -f
      - pip install .
      - pip install -r docs/requirements.txt
      
sphinx:
  configuration: docs/source/conf.py
