version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections
      - apt-get install -y ttf-mscorefonts-installer
      - pip install .
      - pip install -r docs/requirements.txt
      
sphinx:
  configuration: docs/source/conf.py
