version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install matplotlib>=3.6.0
      - pip install .
      - pip install -r docs/requirements.txt
      
sphinx:
  configuration: docs/source/conf.py
